Added profile pictures for linked accounts
Jonathan204/SyncStream pull request #147
Opened 2021-04-04 21:24 UTC by ColeVoelpel

Adds profile pictures for spotify linked accounts. Still renders the default icon if the account is not linked yet. 

Note: Accidentally commit to main with these changes but they were reverted. Just leaving this comment here as documentation

2021-04-04 21:36 UTC, mjbathtub approved these changes
beautiful

2021-04-04 23:05 UTC, chris-mega approved these changes
awesome!

2021-04-04 23:39 UTC, chris-mega requested changes

2021-04-04 23:39 UTC, chris-mega commented on client/src/components/Profile/Profile.js
> +                  <Image
I think we can save some line of code by replacing lines 197-215 with
```
<Image
  src={ profilePic ? profilePic : profilePicture }
  ...
/>
```

2021-04-05 21:32 UTC, chris-mega approved these changes

2021-04-05 21:33 UTC, merged